### ISSUE TITLE
Node Span Strong

### ISSUE THREAD

**Issue by cymkd** [datocms/sveltekit-demo#2]
Hey! 

Just to :)
the Span.svelte could use:

{#if node?.marks?.includes('strong')}
<strong>{node.value}</strong>
{:else}
{node.value}
{/if}

And I guess some more scenarios for the marks

**Comment by matjack1** [comment]
Sorry @vsimak I'm not getting your suggestion, could you please provide a bit more details or maybe a pointer to the code that you would like to change?
